spring:
  application:
    name: misfinanzas
  datasource:
    url: jdbc:postgresql://localhost:5432/misfinanzas
    username: postgres
    password: ${DB_PASSWORD:devpass}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging:
  level:
    org.hibernate.SQL: debug

misfinanzas:
  security:
    jwt:
      secret: ${JWT_SECRET:cambia-este-valor-en-produccion-por-uno-largo-y-aleatorio}
      access-token-minutes: 15
      refresh-token-days: 30
    google:
      client-id: 296166856263-u9ubd4bmvn1nbsnj60iffebpu70p56r9.apps.googleusercontent.com